[W 2024-02-10 12:21:12.586 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-02-10 12:21:12.760 ServerApp] Extension package jupyterlab_jupytext took 0.1511s to import
[W 2024-02-10 12:21:12.760 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-02-10 12:21:12.763 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-02-10 12:21:12.768 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-02-10 12:21:12.774 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-02-10 12:21:12.775 ServerApp] jupyterlab_jupytext | extension was successfully linked.
[I 2024-02-10 12:21:13.302 ServerApp] Extension package jupyter_tensorboard took 0.1878s to import
[W 2024-02-10 12:21:13.302 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_tensorboard. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-02-10 12:21:13.302 ServerApp] jupyter_tensorboard | extension was found and enabled by notebook_shim. Consider moving the extension to Jupyter Server's extension paths.
[I 2024-02-10 12:21:13.302 ServerApp] jupyter_tensorboard | extension was successfully linked.
[I 2024-02-10 12:21:13.302 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-02-10 12:21:13.357 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-02-10 12:21:13.359 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-02-10 12:21:13.361 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-02-10 12:21:15.043 ServerApp] jupyter_tensorboard extension loaded.
[I 2024-02-10 12:21:15.043 ServerApp] jupyter_tensorboard | extension was successfully loaded.
[I 2024-02-10 12:21:15.065 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.10/dist-packages/jupyterlab
[I 2024-02-10 12:21:15.065 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 2024-02-10 12:21:15.066 LabApp] Extension Manager is 'pypi'.
[I 2024-02-10 12:21:15.068 ServerApp] jupyterlab | extension was successfully loaded.
[W 2024-02-10 12:21:15.068 ServerApp] [Jupytext Server Extension] Async contents managers like AsyncLargeFileManager are not supported at the moment (https://github.com/mwouts/jupytext/issues/1020). We will derive a contents manager from LargeFileManager instead.
[I 2024-02-10 12:21:15.069 ServerApp] [Jupytext Server Extension] Deriving a JupytextContentsManager from LargeFileManager
[I 2024-02-10 12:21:15.070 ServerApp] jupyterlab_jupytext | extension was successfully loaded.
[I 2024-02-10 12:21:15.070 ServerApp] The port 8888 is already in use, trying another port.
[I 2024-02-10 12:21:15.071 ServerApp] Serving notebooks from local directory: /home/mjovanovic/Work/PointNet_Segmentation
[I 2024-02-10 12:21:15.071 ServerApp] Jupyter Server 2.12.4 is running at:
[I 2024-02-10 12:21:15.071 ServerApp] http://localhost:8889/lab?token=10a39b630c1cba55c394247d5f2bf523dcfd8b9f068b4309
[I 2024-02-10 12:21:15.071 ServerApp]     http://127.0.0.1:8889/lab?token=10a39b630c1cba55c394247d5f2bf523dcfd8b9f068b4309
[I 2024-02-10 12:21:15.071 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-02-10 12:21:15.074 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/mjovanovic/.local/share/jupyter/runtime/jpserver-2764872-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/lab?token=10a39b630c1cba55c394247d5f2bf523dcfd8b9f068b4309
        http://127.0.0.1:8889/lab?token=10a39b630c1cba55c394247d5f2bf523dcfd8b9f068b4309
[I 2024-02-10 12:21:15.885 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2024-02-10 12:22:06.158 ServerApp] 404 GET /hub/api (@127.0.0.1) 32.65ms referer=None
[W 2024-02-10 12:22:06.160 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.79ms referer=None
[W 2024-02-10 12:22:06.283 ServerApp] 404 GET /tree? (@127.0.0.1) 2.29ms referer=None
[W 2024-02-10 12:22:06.286 ServerApp] 404 GET /tree? (@127.0.0.1) 2.06ms referer=None
[W 2024-02-10 12:22:06.330 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 12:22:06.334 ServerApp] 403 GET /api/kernelspecs?1707596526299 (@127.0.0.1) 4.63ms referer=None
[W 2024-02-10 12:22:06.337 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 12:22:06.338 ServerApp] 403 GET /api/kernels?1707596526301 (@127.0.0.1) 3.55ms referer=None
[W 2024-02-10 12:22:06.339 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 12:22:06.340 ServerApp] 403 GET /api/kernelspecs?1707596526304 (@127.0.0.1) 5.58ms referer=None
[W 2024-02-10 12:22:06.341 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 12:22:06.343 ServerApp] 403 GET /api/kernels?1707596526307 (@127.0.0.1) 7.36ms referer=None
[W 2024-02-10 12:22:06.348 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 12:22:06.349 ServerApp] 403 GET /api/kernels?1707596526315 (@127.0.0.1) 5.77ms referer=None
[W 2024-02-10 12:22:06.350 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 12:22:06.351 ServerApp] 403 GET /api/sessions?1707596526316 (@127.0.0.1) 7.27ms referer=None
[W 2024-02-10 12:22:06.353 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 12:22:06.354 ServerApp] 403 GET /api/kernels?1707596526318 (@127.0.0.1) 8.39ms referer=None
[W 2024-02-10 12:22:06.355 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 12:22:06.356 ServerApp] 403 GET /api/sessions?1707596526319 (@127.0.0.1) 9.89ms referer=None
[W 2024-02-10 12:22:06.360 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 12:22:06.361 ServerApp] 403 GET /api/kernelspecs?1707596526340 (@127.0.0.1) 2.88ms referer=None
[W 2024-02-10 12:22:06.361 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 12:22:06.362 ServerApp] 403 GET /api/kernelspecs?1707596526348 (@127.0.0.1) 3.67ms referer=None
[W 2024-02-10 12:22:59.294 ServerApp] 404 GET /hub/api (@127.0.0.1) 2.51ms referer=None
[W 2024-02-10 12:22:59.297 ServerApp] 404 GET /hub/api (@127.0.0.1) 2.20ms referer=None
[W 2024-02-10 12:22:59.303 ServerApp] 404 GET /tree? (@127.0.0.1) 2.08ms referer=None
[W 2024-02-10 12:22:59.354 ServerApp] 404 GET /tree? (@127.0.0.1) 2.35ms referer=None
[W 2024-02-10 12:22:59.443 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 12:22:59.444 ServerApp] 403 GET /api/kernelspecs?1707596579324 (@127.0.0.1) 1.40ms referer=None
[W 2024-02-10 12:22:59.444 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 12:22:59.445 ServerApp] 403 GET /api/kernels?1707596579327 (@127.0.0.1) 1.92ms referer=None
[W 2024-02-10 12:22:59.446 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 12:22:59.446 ServerApp] 403 GET /api/kernels?1707596579361 (@127.0.0.1) 1.15ms referer=None
[W 2024-02-10 12:22:59.446 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 12:22:59.447 ServerApp] 403 GET /api/sessions?1707596579396 (@127.0.0.1) 1.68ms referer=None
[W 2024-02-10 12:22:59.464 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 12:22:59.465 ServerApp] 403 GET /api/kernelspecs?1707596579404 (@127.0.0.1) 1.34ms referer=None
[W 2024-02-10 12:22:59.465 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 12:22:59.465 ServerApp] 403 GET /api/kernels?1707596579408 (@127.0.0.1) 1.87ms referer=None
[W 2024-02-10 12:22:59.466 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 12:22:59.467 ServerApp] 403 GET /api/kernels?1707596579442 (@127.0.0.1) 1.13ms referer=None
[W 2024-02-10 12:22:59.467 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 12:22:59.468 ServerApp] 403 GET /api/sessions?1707596579444 (@127.0.0.1) 1.65ms referer=None
[W 2024-02-10 13:00:29.691 ServerApp] 404 GET /hub/api (@127.0.0.1) 2.55ms referer=None
[W 2024-02-10 13:00:29.693 ServerApp] 404 GET /hub/api (@127.0.0.1) 2.17ms referer=None
[W 2024-02-10 13:00:29.840 ServerApp] 404 GET /tree? (@127.0.0.1) 2.30ms referer=None
[W 2024-02-10 13:00:29.915 ServerApp] 404 GET /tree? (@127.0.0.1) 2.10ms referer=None
[W 2024-02-10 13:00:30.132 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:00:30.134 ServerApp] 403 GET /api/kernelspecs?1707598830029 (@127.0.0.1) 2.73ms referer=None
[W 2024-02-10 13:00:30.134 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:00:30.135 ServerApp] 403 GET /api/kernels?1707598830032 (@127.0.0.1) 3.73ms referer=None
[W 2024-02-10 13:00:30.141 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:00:30.142 ServerApp] 403 GET /api/kernelspecs?1707598830058 (@127.0.0.1) 3.54ms referer=None
[W 2024-02-10 13:00:30.145 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:00:30.146 ServerApp] 403 GET /api/kernels?1707598830060 (@127.0.0.1) 3.71ms referer=None
[W 2024-02-10 13:00:30.147 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:00:30.148 ServerApp] 403 GET /api/kernels?1707598830069 (@127.0.0.1) 4.78ms referer=None
[W 2024-02-10 13:00:30.149 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:00:30.150 ServerApp] 403 GET /api/sessions?1707598830070 (@127.0.0.1) 5.89ms referer=None
[W 2024-02-10 13:00:30.150 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:00:30.151 ServerApp] 403 GET /api/kernels?1707598830096 (@127.0.0.1) 6.97ms referer=None
[W 2024-02-10 13:00:30.152 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:00:30.153 ServerApp] 403 GET /api/sessions?1707598830097 (@127.0.0.1) 8.09ms referer=None
[W 2024-02-10 13:00:30.407 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:00:30.408 ServerApp] 403 GET /api/kernelspecs?1707598830315 (@127.0.0.1) 2.16ms referer=None
[W 2024-02-10 13:00:33.764 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.85ms referer=None
[W 2024-02-10 13:00:33.766 ServerApp] 404 GET /hub/api (@127.0.0.1) 1.34ms referer=None
[W 2024-02-10 13:00:33.857 ServerApp] 404 GET /tree? (@127.0.0.1) 1.53ms referer=None
[W 2024-02-10 13:00:33.858 ServerApp] 404 GET /tree? (@127.0.0.1) 1.20ms referer=None
[W 2024-02-10 13:00:33.897 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:00:33.898 ServerApp] 403 GET /api/kernelspecs?1707598833862 (@127.0.0.1) 1.61ms referer=None
[W 2024-02-10 13:00:33.900 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:00:33.900 ServerApp] 403 GET /api/kernels?1707598833863 (@127.0.0.1) 1.99ms referer=None
[W 2024-02-10 13:00:33.901 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:00:33.901 ServerApp] 403 GET /api/kernelspecs?1707598833865 (@127.0.0.1) 2.53ms referer=None
[W 2024-02-10 13:00:33.901 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:00:33.902 ServerApp] 403 GET /api/kernels?1707598833866 (@127.0.0.1) 3.05ms referer=None
[W 2024-02-10 13:00:33.902 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:00:33.903 ServerApp] 403 GET /api/kernels?1707598833869 (@127.0.0.1) 3.58ms referer=None
[W 2024-02-10 13:00:33.903 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:00:33.903 ServerApp] 403 GET /api/sessions?1707598833870 (@127.0.0.1) 4.15ms referer=None
[W 2024-02-10 13:00:33.904 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:00:33.905 ServerApp] 403 GET /api/kernels?1707598833871 (@127.0.0.1) 1.33ms referer=None
[W 2024-02-10 13:00:33.905 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:00:33.906 ServerApp] 403 GET /api/sessions?1707598833872 (@127.0.0.1) 1.75ms referer=None
[W 2024-02-10 13:02:45.353 ServerApp] 404 GET /hub/api (@127.0.0.1) 2.51ms referer=None
[W 2024-02-10 13:02:45.355 ServerApp] 404 GET /hub/api (@127.0.0.1) 3.72ms referer=None
[W 2024-02-10 13:02:45.391 ServerApp] 404 GET /tree? (@127.0.0.1) 1.98ms referer=None
[W 2024-02-10 13:02:45.393 ServerApp] 404 GET /tree? (@127.0.0.1) 1.75ms referer=None
[W 2024-02-10 13:02:45.460 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:02:45.461 ServerApp] 403 GET /api/kernelspecs?1707598965419 (@127.0.0.1) 2.39ms referer=None
[W 2024-02-10 13:02:45.462 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:02:45.463 ServerApp] 403 GET /api/kernels?1707598965420 (@127.0.0.1) 3.23ms referer=None
[W 2024-02-10 13:02:45.465 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:02:45.466 ServerApp] 403 GET /api/kernelspecs?1707598965423 (@127.0.0.1) 3.04ms referer=None
[W 2024-02-10 13:02:45.467 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:02:45.467 ServerApp] 403 GET /api/kernels?1707598965424 (@127.0.0.1) 3.89ms referer=None
[W 2024-02-10 13:02:45.468 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:02:45.469 ServerApp] 403 GET /api/kernels?1707598965435 (@127.0.0.1) 4.82ms referer=None
[W 2024-02-10 13:02:45.469 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:02:45.470 ServerApp] 403 GET /api/sessions?1707598965436 (@127.0.0.1) 5.78ms referer=None
[W 2024-02-10 13:02:45.471 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:02:45.471 ServerApp] 403 GET /api/kernels?1707598965437 (@127.0.0.1) 6.70ms referer=None
[W 2024-02-10 13:02:45.473 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:02:45.473 ServerApp] 403 GET /api/sessions?1707598965438 (@127.0.0.1) 1.72ms referer=None
[W 2024-02-10 13:02:45.479 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:02:45.480 ServerApp] 403 GET /api/kernelspecs?1707598965472 (@127.0.0.1) 1.49ms referer=None
[W 2024-02-10 13:02:45.483 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/mjovanovic/.local/lib/python3.10/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/base/handlers.py", line 763, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
[W 2024-02-10 13:02:45.484 ServerApp] 403 GET /api/kernelspecs?1707598965478 (@127.0.0.1) 1.48ms referer=None
