
CUDA Environment Info

-- JOB METADATA --
slurm job id: 2362027
batch size: 3000
learning rate: 0.010
epochs: 30

loading packages..
TensorFlow version 2.6.0
Keras version 2.6.0

loading data..
X shape: (355887, 1053, 4)
Y shape: (355887, 1053, 1)
Size of batches: 0.05 GB

Number of training samples: 249121
Number of validation samples: 53383
Number of test samples: 53383
Y train: (249121, 1053, 1)
X train: (249121, 1053, 4)


Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/conv_utils.py", line 69, in normalize_tuple
    value_tuple = tuple(value)
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/pnet_train_loop.py", line 114, in <module>
    pnet_omicron = PointNet_omicron(shape=(None, X.shape[1], 4),
  File "/localscratch/russbate.2362027.0/scripts/pnet_models.py", line 183, in PointNet_omicron
    max_pool = layers.MaxPool1D(pool_size=shape[0], name='tnet_0_MaxPool')(block_2_masked)
  File "/usr/local/lib/python3.8/dist-packages/keras/layers/pooling.py", line 187, in __init__
    super(MaxPooling1D, self).__init__(
  File "/usr/local/lib/python3.8/dist-packages/keras/layers/pooling.py", line 59, in __init__
    self.pool_size = conv_utils.normalize_tuple(pool_size, 1, 'pool_size')
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/conv_utils.py", line 71, in normalize_tuple
    raise ValueError('The `' + name + '` argument must be a tuple of ' +
ValueError: The `pool_size` argument must be a tuple of 1 integers. Received: None
